# 修改记录:
# 1. 仅保留workflow_dispatch手动触发
# 2. 设置push: false禁止推送镜像
# 3. 修改target为export-binary直接导出文件
# 4. 添加文件校验步骤确保获取正确平台的二进制

name: bin-image

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

env:
  REPO_SLUG: moby/vpnkit-bin
jobs:
  build:
    uses: ./.github/workflows/bake-distribute-mp.yml
    with:
      target: export-binary  # 使用导出文件的目标
      push: false
      cache: false
      meta-image: moby/vpnkit-bin
      meta-tags: |
        type=semver,pattern={{version}}
        type=ref,event=branch
        type=ref,event=pr
        type=sha
    secrets:
      login-username: ${{ secrets.DOCKERHUB_USERNAME }}
      login-password: ${{ secrets.DOCKERHUB_TOKEN }}

  upload-binary:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify binary platform
        run: |
          file ./dist/vpnkit  # 验证文件类型（应显示 x86-64 架构）
          chmod +x ./dist/vpnkit  # 添加执行权限

      - name: Upload vpnkit as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vpnkit-binary
          path: ./dist/vpnkit
